const BMI_TRANSLATIONS = {
    en: {
        title: "BMI Calculator",
        name: "Name",
        surname: "Surname",
        age: "Age",
        gender: "Gender",
        male: "Male",
        female: "Female",
        activityLevel: "Activity Level",
        sedentary: "Sedentary (little or no exercise)",
        lightlyActive: "Lightly active (light exercise/sports 1-3 days/week)",
        moderatelyActive: "Moderately active (moderate exercise/sports 3-5 days/week)",
        veryActive: "Very active (hard exercise/sports 6-7 days a week)",
        extraActive: "Extra active (very hard exercise/sports & physical job)",
        dietType: "Diet Type",
        balanced: "Balanced",
        keto: "Keto",
        paleo: "Paleo",
        highProtein: "High Protein",
        weight: "Weight",
        height: "Height",
        calculate: "Calculate",
        clear: "Clear",
        bodyMassIndex: "Body Mass Index",
        healthStatus: "Health Status",
        bmr: "Basal Metabolic Rate (BMR)",
        tdee: "Daily Energy Needs (TDEE)",
        macroGuide: "Daily Macronutrient Guide",
        protein: "Protein",
        carbs: "Carbs",
        fats: "Fats",
        underweight: "Underweight",
        normal: "Normal weight",
        overweight: "Overweight",
        obese: "Obese",
        ideal: "Ideal",
        kcalDayResting: "kcal / day (Resting)",
        kcalDayActive: "kcal / day (Active)",
        previousRecords: "Previous Records",
        viewRecordsFor: "View records for:",
        allUsers: "All Users",
        exportCsv: "Export CSV",
        advancedConverter: "Advanced Real-Time Unit Converter",
        weightConverter: "Weight Converter",
        heightConverter: "Height Converter",
        visitors: "Visitors",
        darkMode: "Dark Mode",
        lightMode: "Light Mode",
        enterName: "Enter your name",
        enterSurname: "Enter your surname",
        bodyMeasurements: "Body Measurements (for Body Fat %)",
        neckCircumference: "Neck Circumference (cm)",
        waistCircumference: "Waist Circumference (cm)",
        hipCircumference: "Hip Circumference (cm)",
        hipNote: "(required for female)",
        goalWeight: "Goal Weight",
        downloadReport: "Download Health Report (PDF)",
        noRecords: "No records to export.",
        validationError: "Please enter valid positive numbers for weight, height, and age.",
        bodyFatNavy: "Body Fat % (Navy Method)",
        waistToHeight: "Waist-to-Height Ratio",
        weightVelocity: "Weight Velocity",
        projectedGoal: "Projected Goal Date",
        basedOnTrend: "Based on current trend",
    },
    es: {
        title: "Calculadora de IMC",
        name: "Nombre",
        surname: "Apellido",
        age: "Edad",
        gender: "Género",
        male: "Masculino",
        female: "Femenino",
        activityLevel: "Nivel de Actividad",
        sedentary: "Sedentario (poco o ningún ejercicio)",
        lightlyActive: "Ligeramente activo (ejercicio ligero 1-3 días/semana)",
        moderatelyActive: "Moderadamente activo (ejercicio moderado 3-5 días/semana)",
        veryActive: "Muy activo (ejercicio intenso 6-7 días/semana)",
        extraActive: "Extra activo (ejercicio muy intenso y trabajo físico)",
        dietType: "Tipo de Dieta",
        balanced: "Equilibrada",
        keto: "Keto",
        paleo: "Paleo",
        highProtein: "Alta en Proteínas",
        weight: "Peso",
        height: "Altura",
        calculate: "Calcular",
        clear: "Limpiar",
        bodyMassIndex: "Índice de Masa Corporal",
        healthStatus: "Estado de Salud",
        bmr: "Tasa Metabólica Basal (TMB)",
        tdee: "Necesidades Energéticas Diarias (TDEE)",
        macroGuide: "Guía de Macronutrientes Diarios",
        protein: "Proteína",
        carbs: "Carbohidratos",
        fats: "Grasas",
        underweight: "Bajo peso",
        normal: "Peso normal",
        overweight: "Sobrepeso",
        obese: "Obesidad",
        ideal: "Ideal",
        kcalDayResting: "kcal / día (Reposo)",
        kcalDayActive: "kcal / día (Activo)",
        previousRecords: "Registros Anteriores",
        viewRecordsFor: "Ver registros de:",
        allUsers: "Todos los Usuarios",
        exportCsv: "Exportar CSV",
        advancedConverter: "Convertidor de Unidades Avanzado",
        weightConverter: "Convertidor de Peso",
        heightConverter: "Convertidor de Altura",
        visitors: "Visitantes",
        darkMode: "Modo Oscuro",
        lightMode: "Modo Claro",
        enterName: "Ingrese su nombre",
        enterSurname: "Ingrese su apellido",
        bodyMeasurements: "Medidas Corporales (para % de Grasa)",
        neckCircumference: "Circunferencia del Cuello (cm)",
        waistCircumference: "Circunferencia de la Cintura (cm)",
        hipCircumference: "Circunferencia de la Cadera (cm)",
        hipNote: "(requerido para mujeres)",
        goalWeight: "Peso Objetivo",
        downloadReport: "Descargar Informe de Salud (PDF)",
        noRecords: "No hay registros para exportar.",
        validationError: "Por favor ingrese números positivos válidos para peso, altura y edad.",
        bodyFatNavy: "% de Grasa Corporal (Método Navy)",
        waistToHeight: "Relación Cintura-Altura",
        weightVelocity: "Velocidad de Peso",
        projectedGoal: "Fecha Proyectada de Meta",
        basedOnTrend: "Basado en la tendencia actual",
    },
    fr: {
        title: "Calculateur d'IMC",
        name: "Prénom",
        surname: "Nom",
        age: "Âge",
        gender: "Genre",
        male: "Homme",
        female: "Femme",
        activityLevel: "Niveau d'Activité",
        sedentary: "Sédentaire (peu ou pas d'exercice)",
        lightlyActive: "Légèrement actif (exercice léger 1-3 jours/semaine)",
        moderatelyActive: "Modérément actif (exercice modéré 3-5 jours/semaine)",
        veryActive: "Très actif (exercice intense 6-7 jours/semaine)",
        extraActive: "Extra actif (exercice très intense et travail physique)",
        dietType: "Type de Régime",
        balanced: "Équilibré",
        keto: "Keto",
        paleo: "Paléo",
        highProtein: "Riche en Protéines",
        weight: "Poids",
        height: "Taille",
        calculate: "Calculer",
        clear: "Effacer",
        bodyMassIndex: "Indice de Masse Corporelle",
        healthStatus: "État de Santé",
        bmr: "Métabolisme de Base (MB)",
        tdee: "Besoins Énergétiques Journaliers (TDEE)",
        macroGuide: "Guide des Macronutriments Quotidiens",
        protein: "Protéines",
        carbs: "Glucides",
        fats: "Lipides",
        underweight: "Insuffisance pondérale",
        normal: "Poids normal",
        overweight: "Surpoids",
        obese: "Obésité",
        ideal: "Idéal",
        kcalDayResting: "kcal / jour (Repos)",
        kcalDayActive: "kcal / jour (Actif)",
        previousRecords: "Historique",
        viewRecordsFor: "Voir les records de :",
        allUsers: "Tous les Utilisateurs",
        exportCsv: "Exporter CSV",
        advancedConverter: "Convertisseur d'Unités Avancé",
        weightConverter: "Convertisseur de Poids",
        heightConverter: "Convertisseur de Taille",
        visitors: "Visiteurs",
        darkMode: "Mode Sombre",
        lightMode: "Mode Clair",
        enterName: "Entrez votre prénom",
        enterSurname: "Entrez votre nom",
        bodyMeasurements: "Mesures Corporelles (pour % de graisse)",
        neckCircumference: "Tour de Cou (cm)",
        waistCircumference: "Tour de Taille (cm)",
        hipCircumference: "Tour de Hanches (cm)",
        hipNote: "(requis pour les femmes)",
        goalWeight: "Poids Objectif",
        downloadReport: "Télécharger le Rapport de Santé (PDF)",
        noRecords: "Aucun enregistrement à exporter.",
        validationError: "Veuillez entrer des nombres positifs valides pour le poids, la taille et l'âge.",
        bodyFatNavy: "% de Graisse Corporelle (Méthode Navy)",
        waistToHeight: "Rapport Taille-Hauteur",
        weightVelocity: "Vélocité du Poids",
        projectedGoal: "Date d'Objectif Projetée",
        basedOnTrend: "Basé sur la tendance actuelle",
    },
};
